name: Deploy Admin Panel

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /var/www/artisenleather/admin
            git reset --hard
            git pull origin main

            # মেমোরি লিমিট নিশ্চিত করা (Swap ব্যবহারের জন্য)
            export NODE_OPTIONS="--max-old-space-size=1536"

            npm install
            rm -rf dist
            npm run build

            # পারমিশন ফিক্স এবং এনজিনেক্স রিস্টার্ট
            sudo chown -R www-data:www-data /var/www/artisenleather/admin/dist
            sudo chmod -R 755 /var/www/artisenleather/admin/dist
            sudo systemctl restart nginx
            echo "CI/CD Deployment Successful!"
